name: portfolio

on:
  push:
    branches: [main]

#those are jobs inside the workflow
jobs:
# this is github runner, each job runs a runner
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to users
        run: echo "Hello dosto"

      - name: Say hello to username
        run: echo "Hello ${{ github.actor }}"
#this is the name of the job 2
  details:
    runs-on: ubuntu-latest

    steps:
      - name: Version of Python and Docker
        run: docker --version && python --version


