name: hello

on:
  push:
    branches: [main]

jobs:

  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to users
        run: echo "Hello dosto"

      - name: Say hello to username
        run: echo "Hello ${{ github.actor }}"

  details:
    runs-on: ubuntu-latest

    steps:
      - name: Version of Python and Docker
        run: docker --version && python --version
